GET http://127.0.0.1:8000/api/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cC6IkpXVCJ9.eyJlbWFpbCI6Im9heTc4MjAwNkBnbWFpbC5jb20iLCJleHAiOjE3NjEzMjkwMzUsImlhdCI6MTc2MTA2OTgzNSwicm9sZSI6InN0dWRlbnQiLCJ1c2VyX2lkIjo2fQ.Oxr1VbB2ek7EgQLB0U4vABvGVaoUX-3UUpo_vTyY_0M